/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRouteImport } from './routes/track'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ProductCodeRouteImport } from './routes/product.$code'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminInquiriesRouteImport } from './routes/_authenticated/admin.inquiries'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminWholesaleRouteImport } from './routes/_authenticated/admin.wholesale'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCodeRoute = ProductCodeRouteImport.update({
  id: '/product/$code',
  path: '/product/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInquiriesRoute =
  AuthenticatedAdminInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWholesaleRoute =
  AuthenticatedAdminWholesaleRouteImport.update({
    id: '/wholesale',
    path: '/wholesale',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/wholesale': typeof WholesaleRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/product/$code': typeof ProductCodeRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/wholesale': typeof AuthenticatedAdminWholesaleRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/wholesale': typeof WholesaleRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$code': typeof ProductCodeRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/wholesale': typeof AuthenticatedAdminWholesaleRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/wholesale': typeof WholesaleRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/product/$code': typeof ProductCodeRoute
  '/_authenticated/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/wholesale': typeof AuthenticatedAdminWholesaleRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/track'
    | '/wholesale'
    | '/admin'
    | '/category/$slug'
    | '/product/$code'
    | '/admin/inquiries'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/wholesale'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/track'
    | '/wholesale'
    | '/category/$slug'
    | '/product/$code'
    | '/admin/inquiries'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/wholesale'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/track'
    | '/wholesale'
    | '/_authenticated/admin'
    | '/category/$slug'
    | '/product/$code'
    | '/_authenticated/admin/inquiries'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/wholesale'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  WholesaleRoute: typeof WholesaleRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductCodeRoute: typeof ProductCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$code': {
      id: '/product/$code'
      path: '/product/$code'
      fullPath: '/product/$code'
      preLoaderRoute: typeof ProductCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inquiries': {
      id: '/_authenticated/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AuthenticatedAdminInquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/wholesale': {
      id: '/_authenticated/admin/wholesale'
      path: '/wholesale'
      fullPath: '/admin/wholesale'
      preLoaderRoute: typeof AuthenticatedAdminWholesaleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminInquiriesRoute: typeof AuthenticatedAdminInquiriesRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminWholesaleRoute: typeof AuthenticatedAdminWholesaleRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminInquiriesRoute: AuthenticatedAdminInquiriesRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminWholesaleRoute: AuthenticatedAdminWholesaleRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  WholesaleRoute: WholesaleRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductCodeRoute: ProductCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
